### ISSUE TITLE
为什么删除了我的好友并且无法重新加?

### ISSUE THREAD

**Issue by alsace5** [kj415j45/kjBot#141]
我并没有盈利或者短时间发送大量命令，而且它自动退出了

**Comment by BobLiu0518** [comment]
因为之前被恶意举报(可能) 所以把所有的好友和群都san掉了
然后不是不能重新加，而是等kj415j45手动验证（因为之前kjBot被封过一小会儿）
如果想要了解更多欢迎加入 kjBot Dev (Beta) 群了解，群号805348195

**Comment by kj415j45** [comment]
ng计划进行中，更多细节原因不透露
